/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
  EnvironmentIdInfoReply,
  EnvironmentListReply,
  ExpanseCreateReply,
  ExpanseIdInfoReply,
  ExpanseListReply,
  ManagerAuthReply,
  ManagerCreateReply,
  ManagerInfoReply,
  ManagerListReply,
  ProjectIdInfoReply,
  ProjectListReply,
} from "./schemas";

export const getManagerControllerHandleManagerInfoResponseMock = (
  overrideResponse: Partial<Extract<ManagerInfoReply, object>> = {},
): ManagerInfoReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerListResponseMock = (
  overrideResponse: Partial<Extract<ManagerListReply, object>> = {},
): ManagerListReply => ({
  data: {
    ...{
      managers: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        username: faker.string.alpha({ length: { min: 10, max: 20 } }),
        role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerAuthResponseMock = (
  overrideResponse: Partial<Extract<ManagerAuthReply, object>> = {},
): ManagerAuthReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  meta: { ...{ jwt: faker.string.alpha({ length: { min: 10, max: 20 } }) } },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerCreateResponseMock = (
  overrideResponse: Partial<Extract<ManagerCreateReply, object>> = {},
): ManagerCreateReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseIdInfoResponseMock = (
  overrideResponse: Partial<Extract<ExpanseIdInfoReply, object>> = {},
): ExpanseIdInfoReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseListResponseMock = (
  overrideResponse: Partial<Extract<ExpanseListReply, object>> = {},
): ExpanseListReply => ({
  data: {
    ...{
      expanse: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseCreateResponseMock = (
  overrideResponse: Partial<Extract<ExpanseCreateReply, object>> = {},
): ExpanseCreateReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseUpdateResponseMock = (
  overrideResponse: Partial<Extract<ExpanseIdInfoReply, object>> = {},
): ExpanseIdInfoReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseDeleteResponseMock = (
  overrideResponse: Partial<Extract<ExpanseIdInfoReply, object>> = {},
): ExpanseIdInfoReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentIdInfoResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentListResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentListReply, object>> = {},
): EnvironmentListReply => ({
  data: {
    ...{
      environment: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        stage: faker.helpers.arrayElement([
          "DEV",
          "TEST",
          "PREPROD",
          "PROD",
        ] as const),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentCreateResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentDeleteResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentUpdateResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectListResponseMock = (
  overrideResponse: Partial<Extract<ProjectListReply, object>> = {},
): ProjectListReply => ({
  data: {
    ...{
      project: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectIdInfoResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectCreateResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectUpdateResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectDeleteResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});
