/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
  EnvironmentIdInfoReply,
  EnvironmentListReply,
  ExpanseCreateReply,
  ExpanseIdInfoReply,
  ExpanseInfoReply,
  ExpanseListReply,
  ManagerAuthReply,
  ManagerCreateReply,
  ManagerInfoReply,
  ManagerListReply,
  ProjectIdInfoReply,
  ProjectListReply,
} from "./schemas";

export const getManagerControllerHandleManagerInfoResponseMock = (
  overrideResponse: Partial<Extract<ManagerInfoReply, object>> = {},
): ManagerInfoReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerListResponseMock = (
  overrideResponse: Partial<Extract<ManagerListReply, object>> = {},
): ManagerListReply => ({
  data: {
    ...{
      managers: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        username: faker.string.alpha({ length: { min: 10, max: 20 } }),
        role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerAuthResponseMock = (
  overrideResponse: Partial<Extract<ManagerAuthReply, object>> = {},
): ManagerAuthReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  meta: { ...{ jwt: faker.string.alpha({ length: { min: 10, max: 20 } }) } },
  ...overrideResponse,
});

export const getManagerControllerHandleManagerCreateResponseMock = (
  overrideResponse: Partial<Extract<ManagerCreateReply, object>> = {},
): ManagerCreateReply => ({
  data: {
    ...{
      manager: {
        ...{
          managerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          username: faker.string.alpha({ length: { min: 10, max: 20 } }),
          password: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          role: faker.helpers.arrayElement(["ROOT", "MANAGER"] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseIdInfoResponseMock = (
  overrideResponse: Partial<Extract<ExpanseIdInfoReply, object>> = {},
): ExpanseIdInfoReply => ({
  data: {
    ...{
      expanses: {
        ...{
          id: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          environment: {
            ...{
              stage: faker.helpers.arrayElement([
                "DEV",
                "TEST",
                "PREPROD",
                "PROD",
              ] as const),
              projects: Array.from(
                { length: faker.number.int({ min: 1, max: 10 }) },
                (_, i) => i + 1,
              ).map(() => ({
                projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
                environmentId: faker.string.alpha({
                  length: { min: 10, max: 20 },
                }),
                title: faker.string.alpha({ length: { min: 10, max: 20 } }),
                url: faker.string.alpha({ length: { min: 10, max: 20 } }),
                createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
                updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
              })),
            },
          },
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseListResponseMock = (
  overrideResponse: Partial<Extract<ExpanseListReply, object>> = {},
): ExpanseListReply => ({
  data: {
    ...{
      expanses: {
        ...{
          id: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          environment: {
            ...{
              stage: faker.helpers.arrayElement([
                "DEV",
                "TEST",
                "PREPROD",
                "PROD",
              ] as const),
              projects: Array.from(
                { length: faker.number.int({ min: 1, max: 10 }) },
                (_, i) => i + 1,
              ).map(() => ({
                projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
                environmentId: faker.string.alpha({
                  length: { min: 10, max: 20 },
                }),
                title: faker.string.alpha({ length: { min: 10, max: 20 } }),
                url: faker.string.alpha({ length: { min: 10, max: 20 } }),
                createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
                updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
              })),
            },
          },
        },
      },
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseCreateResponseMock = (
  overrideResponse: Partial<Extract<ExpanseCreateReply, object>> = {},
): ExpanseCreateReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseUpdateResponseMock = (
  overrideResponse: Partial<Extract<ExpanseInfoReply, object>> = {},
): ExpanseInfoReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getExpanseControllerHandleExpanseDeleteResponseMock = (
  overrideResponse: Partial<Extract<ExpanseInfoReply, object>> = {},
): ExpanseInfoReply => ({
  data: {
    ...{
      expanse: {
        ...{
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentIdInfoResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentListResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentListReply, object>> = {},
): EnvironmentListReply => ({
  data: {
    ...{
      environment: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        stage: faker.helpers.arrayElement([
          "DEV",
          "TEST",
          "PREPROD",
          "PROD",
        ] as const),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentCreateResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentDeleteResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getEnvironmentControllerHandleEnvironmentUpdateResponseMock = (
  overrideResponse: Partial<Extract<EnvironmentIdInfoReply, object>> = {},
): EnvironmentIdInfoReply => ({
  data: {
    ...{
      environment: {
        ...{
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          expanseId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          stage: faker.helpers.arrayElement([
            "DEV",
            "TEST",
            "PREPROD",
            "PROD",
          ] as const),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectListResponseMock = (
  overrideResponse: Partial<Extract<ProjectListReply, object>> = {},
): ProjectListReply => ({
  data: {
    ...{
      project: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
      })),
    },
  },
  meta: { ...{ count: faker.number.float({ fractionDigits: 2 }) } },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectIdInfoResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectCreateResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectUpdateResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getProjectControllerHandleProjectDeleteResponseMock = (
  overrideResponse: Partial<Extract<ProjectIdInfoReply, object>> = {},
): ProjectIdInfoReply => ({
  data: {
    ...{
      project: {
        ...{
          projectId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          environmentId: faker.string.alpha({ length: { min: 10, max: 20 } }),
          title: faker.string.alpha({ length: { min: 10, max: 20 } }),
          url: faker.string.alpha({ length: { min: 10, max: 20 } }),
          createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
          updatedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
        },
      },
    },
  },
  ...overrideResponse,
});

export const getFileControllerHandlerFileCreateMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/files/:projectId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getFileControllerHandlerFileInfoMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/files/:images",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getManagerControllerHandleManagerInfoMockHandler = (
  overrideResponse?:
    | ManagerInfoReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ManagerInfoReply> | ManagerInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/manager/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getManagerControllerHandleManagerInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getManagerControllerHandleManagerListMockHandler = (
  overrideResponse?:
    | ManagerListReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ManagerListReply> | ManagerListReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/manager/list",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getManagerControllerHandleManagerListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getManagerControllerHandleManagerAuthMockHandler = (
  overrideResponse?:
    | ManagerAuthReply
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ManagerAuthReply> | ManagerAuthReply),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/manager/auth",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getManagerControllerHandleManagerAuthResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getManagerControllerHandleManagerCreateMockHandler = (
  overrideResponse?:
    | ManagerCreateReply
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ManagerCreateReply> | ManagerCreateReply),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/manager/create",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getManagerControllerHandleManagerCreateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getExpanseControllerHandleExpanseIdInfoMockHandler = (
  overrideResponse?:
    | ExpanseIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExpanseIdInfoReply> | ExpanseIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/expanse/:expanseId/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExpanseControllerHandleExpanseIdInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getExpanseControllerHandleExpanseListMockHandler = (
  overrideResponse?:
    | ExpanseListReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExpanseListReply> | ExpanseListReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/expanse/list",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExpanseControllerHandleExpanseListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getExpanseControllerHandleExpanseCreateMockHandler = (
  overrideResponse?:
    | ExpanseCreateReply
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ExpanseCreateReply> | ExpanseCreateReply),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/expanse/create",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExpanseControllerHandleExpanseCreateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getExpanseControllerHandleExpanseUpdateMockHandler = (
  overrideResponse?:
    | ExpanseInfoReply
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ExpanseInfoReply> | ExpanseInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/expanse/:expanseId/update",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExpanseControllerHandleExpanseUpdateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getExpanseControllerHandleExpanseDeleteMockHandler = (
  overrideResponse?:
    | ExpanseInfoReply
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ExpanseInfoReply> | ExpanseInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/expanse/:expanseId/delete",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExpanseControllerHandleExpanseDeleteResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getEnvironmentControllerHandleEnvironmentIdInfoMockHandler = (
  overrideResponse?:
    | EnvironmentIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<EnvironmentIdInfoReply> | EnvironmentIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/environment/:environmentId/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEnvironmentControllerHandleEnvironmentIdInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getEnvironmentControllerHandleEnvironmentListMockHandler = (
  overrideResponse?:
    | EnvironmentListReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<EnvironmentListReply> | EnvironmentListReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/environment/list",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEnvironmentControllerHandleEnvironmentListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getEnvironmentControllerHandleEnvironmentCreateMockHandler = (
  overrideResponse?:
    | EnvironmentIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<EnvironmentIdInfoReply> | EnvironmentIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/environment/create",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEnvironmentControllerHandleEnvironmentCreateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getEnvironmentControllerHandleEnvironmentDeleteMockHandler = (
  overrideResponse?:
    | EnvironmentIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<EnvironmentIdInfoReply> | EnvironmentIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/environment/:environmentId/delete",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEnvironmentControllerHandleEnvironmentDeleteResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getEnvironmentControllerHandleEnvironmentUpdateMockHandler = (
  overrideResponse?:
    | EnvironmentIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<EnvironmentIdInfoReply> | EnvironmentIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/environment/:environmentId/update",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEnvironmentControllerHandleEnvironmentUpdateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getProjectControllerHandleProjectListMockHandler = (
  overrideResponse?:
    | ProjectListReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProjectListReply> | ProjectListReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/project/list",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProjectControllerHandleProjectListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getProjectControllerHandleProjectIdInfoMockHandler = (
  overrideResponse?:
    | ProjectIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProjectIdInfoReply> | ProjectIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/project/:projectId/info",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProjectControllerHandleProjectIdInfoResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getProjectControllerHandleProjectCreateMockHandler = (
  overrideResponse?:
    | ProjectIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ProjectIdInfoReply> | ProjectIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/project/create",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProjectControllerHandleProjectCreateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getProjectControllerHandleProjectUpdateMockHandler = (
  overrideResponse?:
    | ProjectIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<ProjectIdInfoReply> | ProjectIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/project/:projectId/update",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProjectControllerHandleProjectUpdateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getProjectControllerHandleProjectDeleteMockHandler = (
  overrideResponse?:
    | ProjectIdInfoReply
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<ProjectIdInfoReply> | ProjectIdInfoReply),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/project/:projectId/delete",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProjectControllerHandleProjectDeleteResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getPortalDocumentationMock = () => [
  getFileControllerHandlerFileCreateMockHandler(),
  getFileControllerHandlerFileInfoMockHandler(),
  getManagerControllerHandleManagerInfoMockHandler(),
  getManagerControllerHandleManagerListMockHandler(),
  getManagerControllerHandleManagerAuthMockHandler(),
  getManagerControllerHandleManagerCreateMockHandler(),
  getExpanseControllerHandleExpanseIdInfoMockHandler(),
  getExpanseControllerHandleExpanseListMockHandler(),
  getExpanseControllerHandleExpanseCreateMockHandler(),
  getExpanseControllerHandleExpanseUpdateMockHandler(),
  getExpanseControllerHandleExpanseDeleteMockHandler(),
  getEnvironmentControllerHandleEnvironmentIdInfoMockHandler(),
  getEnvironmentControllerHandleEnvironmentListMockHandler(),
  getEnvironmentControllerHandleEnvironmentCreateMockHandler(),
  getEnvironmentControllerHandleEnvironmentDeleteMockHandler(),
  getEnvironmentControllerHandleEnvironmentUpdateMockHandler(),
  getProjectControllerHandleProjectListMockHandler(),
  getProjectControllerHandleProjectIdInfoMockHandler(),
  getProjectControllerHandleProjectCreateMockHandler(),
  getProjectControllerHandleProjectUpdateMockHandler(),
  getProjectControllerHandleProjectDeleteMockHandler(),
];
