/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentCreateSchema = zod.object({
  expanseId: zod.string(),
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
});

export type EnvironmentCreateSchema = zod.input<typeof EnvironmentCreateSchema>;
export type EnvironmentCreateSchemaOutput = zod.output<
  typeof EnvironmentCreateSchema
>;
