/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentControllerHandleEnvironmentIdInfoParams = zod.object({
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
});

export type EnvironmentControllerHandleEnvironmentIdInfoParams = zod.input<
  typeof EnvironmentControllerHandleEnvironmentIdInfoParams
>;
export type EnvironmentControllerHandleEnvironmentIdInfoParamsOutput =
  zod.output<typeof EnvironmentControllerHandleEnvironmentIdInfoParams>;
