/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentUpdateSchema = zod.object({
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]).optional(),
});

export type EnvironmentUpdateSchema = zod.input<typeof EnvironmentUpdateSchema>;
export type EnvironmentUpdateSchemaOutput = zod.output<
  typeof EnvironmentUpdateSchema
>;
