/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentListReplyMeta = zod.object({
  count: zod.number().describe("Reply count"),
});

export type EnvironmentListReplyMeta = zod.input<
  typeof EnvironmentListReplyMeta
>;
export type EnvironmentListReplyMetaOutput = zod.output<
  typeof EnvironmentListReplyMeta
>;
