/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentControllerHandleEnvironmentCreateBody = zod.object({
  expanseId: zod.string(),
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
});

export type EnvironmentControllerHandleEnvironmentCreateBody = zod.input<
  typeof EnvironmentControllerHandleEnvironmentCreateBody
>;
export type EnvironmentControllerHandleEnvironmentCreateBodyOutput = zod.output<
  typeof EnvironmentControllerHandleEnvironmentCreateBody
>;
