/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentListReplyData = zod.object({
  environment: zod
    .array(
      zod.object({
        environmentId: zod.string().describe("Environment id"),
        expanseId: zod.string().describe("Expanse id"),
        title: zod.string().describe("Environment title"),
        stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Environment created"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Environment updated"),
      }),
    )
    .describe("Data Environment"),
});

export type EnvironmentListReplyData = zod.input<
  typeof EnvironmentListReplyData
>;
export type EnvironmentListReplyDataOutput = zod.output<
  typeof EnvironmentListReplyData
>;
