/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentControllerHandleEnvironmentListParams = zod.object({
  skip: zod.number().optional(),
  take: zod.number().optional(),
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]).optional(),
});

export type EnvironmentControllerHandleEnvironmentListParams = zod.input<
  typeof EnvironmentControllerHandleEnvironmentListParams
>;
export type EnvironmentControllerHandleEnvironmentListParamsOutput = zod.output<
  typeof EnvironmentControllerHandleEnvironmentListParams
>;
