/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentControllerHandleEnvironmentUpdateBody = zod.object({
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]).optional(),
});

export type EnvironmentControllerHandleEnvironmentUpdateBody = zod.input<
  typeof EnvironmentControllerHandleEnvironmentUpdateBody
>;
export type EnvironmentControllerHandleEnvironmentUpdateBodyOutput = zod.output<
  typeof EnvironmentControllerHandleEnvironmentUpdateBody
>;
