/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentIdInfoReply = zod.object({
  data: zod
    .object({
      environment: zod
        .object({
          environmentId: zod.string().describe("Environment id"),
          expanseId: zod.string().describe("Expanse id"),
          title: zod.string().describe("Environment title"),
          stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
          createdAt: zod.iso
            .datetime({ offset: true })
            .describe("Environment created"),
          updatedAt: zod.iso
            .datetime({ offset: true })
            .describe("Environment updated"),
        })
        .describe("Data Environment"),
    })
    .describe("Reply data"),
});

export type EnvironmentIdInfoReply = zod.input<typeof EnvironmentIdInfoReply>;
export type EnvironmentIdInfoReplyOutput = zod.output<
  typeof EnvironmentIdInfoReply
>;
