/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EnvironmentIdInfoReplyDataEnvironment = zod.object({
  environmentId: zod.string().describe("Environment id"),
  expanseId: zod.string().describe("Expanse id"),
  title: zod.string().describe("Environment title"),
  stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
  createdAt: zod.iso.datetime({ offset: true }).describe("Environment created"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Environment updated"),
});

export type EnvironmentIdInfoReplyDataEnvironment = zod.input<
  typeof EnvironmentIdInfoReplyDataEnvironment
>;
export type EnvironmentIdInfoReplyDataEnvironmentOutput = zod.output<
  typeof EnvironmentIdInfoReplyDataEnvironment
>;
