/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseUpdateSchema = zod.object({
  title: zod.string().optional(),
});

export type ExpanseUpdateSchema = zod.input<typeof ExpanseUpdateSchema>;
export type ExpanseUpdateSchemaOutput = zod.output<typeof ExpanseUpdateSchema>;
