/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseControllerHandleExpanseUpdateBody = zod.object({
  title: zod.string().optional(),
});

export type ExpanseControllerHandleExpanseUpdateBody = zod.input<
  typeof ExpanseControllerHandleExpanseUpdateBody
>;
export type ExpanseControllerHandleExpanseUpdateBodyOutput = zod.output<
  typeof ExpanseControllerHandleExpanseUpdateBody
>;
