/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseListReplyDataExpanse = zod.object({
  id: zod.string().describe("Expanse id"),
  title: zod.string().describe("Expanse title"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Expanse created"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Expanse updated"),
  environment: zod
    .object({
      stage: zod.enum(["DEV", "TEST", "PREPROD", "PROD"]),
      projects: zod
        .array(
          zod.object({
            projectId: zod.string().describe("Project id"),
            environmentId: zod.string().describe("Environment id"),
            title: zod.string().describe("Project title"),
            url: zod.string().describe("Project url"),
            createdAt: zod.iso
              .datetime({ offset: true })
              .describe("Project created"),
            updatedAt: zod.iso
              .datetime({ offset: true })
              .describe("Project updated"),
          }),
        )
        .describe("Environment projects"),
    })
    .describe("Expanse environment"),
});

export type ExpanseListReplyDataExpanse = zod.input<
  typeof ExpanseListReplyDataExpanse
>;
export type ExpanseListReplyDataExpanseOutput = zod.output<
  typeof ExpanseListReplyDataExpanse
>;
