/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseIdInfoReply = zod.object({
  data: zod
    .object({
      expanse: zod
        .object({
          expanseId: zod.string().describe("Expanse id"),
          title: zod.string().describe("Expanse title"),
          createdAt: zod.iso
            .datetime({ offset: true })
            .describe("Expanse created"),
          updatedAt: zod.iso
            .datetime({ offset: true })
            .describe("Expanse updated"),
        })
        .describe("Data Expanse"),
    })
    .describe("Reply data"),
});

export type ExpanseIdInfoReply = zod.input<typeof ExpanseIdInfoReply>;
export type ExpanseIdInfoReplyOutput = zod.output<typeof ExpanseIdInfoReply>;
