/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseCreateSchema = zod.object({
  title: zod.string(),
});

export type ExpanseCreateSchema = zod.input<typeof ExpanseCreateSchema>;
export type ExpanseCreateSchemaOutput = zod.output<typeof ExpanseCreateSchema>;
