/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseListReplyData = zod.object({
  expanse: zod
    .array(
      zod.object({
        expanseId: zod.string().describe("Expanse id"),
        title: zod.string().describe("Expanse title"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Expanse created"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Expanse updated"),
      }),
    )
    .describe("Data Expanse"),
});

export type ExpanseListReplyData = zod.input<typeof ExpanseListReplyData>;
export type ExpanseListReplyDataOutput = zod.output<
  typeof ExpanseListReplyData
>;
