/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseListReplyMeta = zod.object({
  count: zod.number().describe("Reply count"),
});

export type ExpanseListReplyMeta = zod.input<typeof ExpanseListReplyMeta>;
export type ExpanseListReplyMetaOutput = zod.output<
  typeof ExpanseListReplyMeta
>;
