/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseControllerHandleExpanseCreateBody = zod.object({
  title: zod.string(),
});

export type ExpanseControllerHandleExpanseCreateBody = zod.input<
  typeof ExpanseControllerHandleExpanseCreateBody
>;
export type ExpanseControllerHandleExpanseCreateBodyOutput = zod.output<
  typeof ExpanseControllerHandleExpanseCreateBody
>;
