/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseControllerHandleExpanseListParams = zod.object({
  skip: zod.number().optional(),
  take: zod.number().optional(),
  search: zod.string().optional(),
});

export type ExpanseControllerHandleExpanseListParams = zod.input<
  typeof ExpanseControllerHandleExpanseListParams
>;
export type ExpanseControllerHandleExpanseListParamsOutput = zod.output<
  typeof ExpanseControllerHandleExpanseListParams
>;
