/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ExpanseListReply = zod.object({
  data: zod
    .object({
      expanse: zod
        .array(
          zod.object({
            expanseId: zod.string().describe("Expanse id"),
            title: zod.string().describe("Expanse title"),
            createdAt: zod.iso
              .datetime({ offset: true })
              .describe("Expanse created"),
            updatedAt: zod.iso
              .datetime({ offset: true })
              .describe("Expanse updated"),
          }),
        )
        .describe("Data Expanse"),
    })
    .describe("Reply data"),
  meta: zod
    .object({
      count: zod.number().describe("Reply count"),
    })
    .describe("Reply meta"),
});

export type ExpanseListReply = zod.input<typeof ExpanseListReply>;
export type ExpanseListReplyOutput = zod.output<typeof ExpanseListReply>;
