/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerListReplyMeta = zod.object({
  count: zod.number().describe("Reply count"),
});

export type ManagerListReplyMeta = zod.input<typeof ManagerListReplyMeta>;
export type ManagerListReplyMetaOutput = zod.output<
  typeof ManagerListReplyMeta
>;
