/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerAuthReply = zod.object({
  data: zod
    .object({
      manager: zod
        .object({
          managerId: zod.string().describe("Manager id"),
          username: zod.string().describe("Manager username"),
          password: zod.string().optional().describe("Manager password"),
          role: zod.enum(["ROOT", "MANAGER"]).describe("Manager role"),
          createdAt: zod.iso
            .datetime({ offset: true })
            .describe("Manager created"),
          updatedAt: zod.iso
            .datetime({ offset: true })
            .describe("Manager updated"),
        })
        .describe("Data manager"),
    })
    .describe("Reply data"),
  meta: zod
    .object({
      jwt: zod.string().describe("Data manager"),
    })
    .describe("Reply meta"),
});

export type ManagerAuthReply = zod.input<typeof ManagerAuthReply>;
export type ManagerAuthReplyOutput = zod.output<typeof ManagerAuthReply>;
