/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerControllerHandleManagerAuthBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export type ManagerControllerHandleManagerAuthBody = zod.input<
  typeof ManagerControllerHandleManagerAuthBody
>;
export type ManagerControllerHandleManagerAuthBodyOutput = zod.output<
  typeof ManagerControllerHandleManagerAuthBody
>;
