/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerListReply = zod.object({
  data: zod
    .object({
      managers: zod
        .array(
          zod.object({
            managerId: zod.string().describe("Manager id"),
            username: zod.string().describe("Manager username"),
            role: zod.enum(["ROOT", "MANAGER"]).describe("Manager role"),
            createdAt: zod.iso
              .datetime({ offset: true })
              .describe("Manager created"),
            updatedAt: zod.iso
              .datetime({ offset: true })
              .describe("Manager updated"),
          }),
        )
        .describe("Data managers"),
    })
    .describe("Reply data"),
  meta: zod
    .object({
      count: zod.number().describe("Reply count"),
    })
    .describe("Reply meta"),
});

export type ManagerListReply = zod.input<typeof ManagerListReply>;
export type ManagerListReplyOutput = zod.output<typeof ManagerListReply>;
