/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerCreateReplyData = zod.object({
  manager: zod
    .object({
      managerId: zod.string().describe("Manager id"),
      username: zod.string().describe("Manager username"),
      password: zod.string().optional().describe("Manager password"),
      role: zod.enum(["ROOT", "MANAGER"]).describe("Manager role"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Manager created"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Manager updated"),
    })
    .describe("Data manager"),
});

export type ManagerCreateReplyData = zod.input<typeof ManagerCreateReplyData>;
export type ManagerCreateReplyDataOutput = zod.output<
  typeof ManagerCreateReplyData
>;
