/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerControllerHandleManagerCreateBody = zod.object({
  username: zod.string(),
  password: zod.string(),
  role: zod.enum(["ROOT", "MANAGER"]),
});

export type ManagerControllerHandleManagerCreateBody = zod.input<
  typeof ManagerControllerHandleManagerCreateBody
>;
export type ManagerControllerHandleManagerCreateBodyOutput = zod.output<
  typeof ManagerControllerHandleManagerCreateBody
>;
