/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerCreateReplyMeta = zod.object({
  jwt: zod.string().describe("Data manager"),
});

export type ManagerCreateReplyMeta = zod.input<typeof ManagerCreateReplyMeta>;
export type ManagerCreateReplyMetaOutput = zod.output<
  typeof ManagerCreateReplyMeta
>;
