/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerCreateSchema = zod.object({
  username: zod.string(),
  password: zod.string(),
  role: zod.enum(["ROOT", "MANAGER"]),
});

export type ManagerCreateSchema = zod.input<typeof ManagerCreateSchema>;
export type ManagerCreateSchemaOutput = zod.output<typeof ManagerCreateSchema>;
