/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerAuthSchema = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export type ManagerAuthSchema = zod.input<typeof ManagerAuthSchema>;
export type ManagerAuthSchemaOutput = zod.output<typeof ManagerAuthSchema>;
