/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ManagerControllerHandleManagerListParams = zod.object({
  skip: zod.number().optional(),
  take: zod.number().optional(),
  search: zod.string().optional(),
});

export type ManagerControllerHandleManagerListParams = zod.input<
  typeof ManagerControllerHandleManagerListParams
>;
export type ManagerControllerHandleManagerListParamsOutput = zod.output<
  typeof ManagerControllerHandleManagerListParams
>;
