/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectCreateReplyDataProject = zod.object({
  projectId: zod.string().describe("Project id"),
  environmentId: zod.string().describe("Environment id"),
  title: zod.string().describe("Project title"),
  url: zod.string().describe("Project url"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Project created"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Project updated"),
});

export type ProjectCreateReplyDataProject = zod.input<
  typeof ProjectCreateReplyDataProject
>;
export type ProjectCreateReplyDataProjectOutput = zod.output<
  typeof ProjectCreateReplyDataProject
>;
