/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectListReplyData = zod.object({
  project: zod
    .array(
      zod.object({
        projectId: zod.string().describe("Project id"),
        expanseId: zod.string().describe("Expanse id"),
        title: zod.string().describe("Project title"),
        url: zod.string().describe("Project url"),
        createdAt: zod.iso
          .datetime({ offset: true })
          .describe("Project created"),
        updatedAt: zod.iso
          .datetime({ offset: true })
          .describe("Project updated"),
      }),
    )
    .describe("Data Project"),
});

export type ProjectListReplyData = zod.input<typeof ProjectListReplyData>;
export type ProjectListReplyDataOutput = zod.output<
  typeof ProjectListReplyData
>;
