/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectUpdateSchema = zod.object({
  title: zod.string(),
  url: zod.string(),
});

export type ProjectUpdateSchema = zod.input<typeof ProjectUpdateSchema>;
export type ProjectUpdateSchemaOutput = zod.output<typeof ProjectUpdateSchema>;
