/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectListReplyMeta = zod.object({
  count: zod.number().describe("Reply count"),
});

export type ProjectListReplyMeta = zod.input<typeof ProjectListReplyMeta>;
export type ProjectListReplyMetaOutput = zod.output<
  typeof ProjectListReplyMeta
>;
