/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectCreateReplyData = zod.object({
  project: zod
    .object({
      projectId: zod.string().describe("Project id"),
      expanseId: zod.string().describe("Expanse id"),
      title: zod.string().describe("Project title"),
      url: zod.string().describe("Project url"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Project created"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Project updated"),
    })
    .describe("Data Project"),
});

export type ProjectCreateReplyData = zod.input<typeof ProjectCreateReplyData>;
export type ProjectCreateReplyDataOutput = zod.output<
  typeof ProjectCreateReplyData
>;
