/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectIdInfoReply = zod.object({
  data: zod
    .object({
      project: zod
        .object({
          projectId: zod.string().describe("Project id"),
          environmentId: zod.string().describe("Environment id"),
          title: zod.string().describe("Project title"),
          url: zod.string().describe("Project url"),
          createdAt: zod.iso
            .datetime({ offset: true })
            .describe("Project created"),
          updatedAt: zod.iso
            .datetime({ offset: true })
            .describe("Project updated"),
        })
        .describe("Data Project"),
    })
    .describe("Reply data"),
});

export type ProjectIdInfoReply = zod.input<typeof ProjectIdInfoReply>;
export type ProjectIdInfoReplyOutput = zod.output<typeof ProjectIdInfoReply>;
