/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectControllerHandleProjectListParams = zod.object({
  skip: zod.number().optional(),
  take: zod.number().optional(),
  search: zod.string().optional(),
});

export type ProjectControllerHandleProjectListParams = zod.input<
  typeof ProjectControllerHandleProjectListParams
>;
export type ProjectControllerHandleProjectListParamsOutput = zod.output<
  typeof ProjectControllerHandleProjectListParams
>;
