/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectControllerHandleProjectCreateBody = zod.object({
  environmentId: zod.string(),
  title: zod.string(),
  url: zod.string(),
});

export type ProjectControllerHandleProjectCreateBody = zod.input<
  typeof ProjectControllerHandleProjectCreateBody
>;
export type ProjectControllerHandleProjectCreateBodyOutput = zod.output<
  typeof ProjectControllerHandleProjectCreateBody
>;
