/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectControllerHandleProjectUpdateBody = zod.object({
  title: zod.string(),
  url: zod.string(),
});

export type ProjectControllerHandleProjectUpdateBody = zod.input<
  typeof ProjectControllerHandleProjectUpdateBody
>;
export type ProjectControllerHandleProjectUpdateBodyOutput = zod.output<
  typeof ProjectControllerHandleProjectUpdateBody
>;
