/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Portal documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ProjectCreateSchema = zod.object({
  expanseId: zod.string(),
  title: zod.string(),
  url: zod.string(),
});

export type ProjectCreateSchema = zod.input<typeof ProjectCreateSchema>;
export type ProjectCreateSchemaOutput = zod.output<typeof ProjectCreateSchema>;
